package com.mystic.atlantis.datagen;

import com.mystic.atlantis.Atlantis;
import com.mystic.atlantis.init.AtlantisEntityInit;
import net.minecraft.core.Holder;
import net.minecraft.core.HolderGetter;
import net.minecraft.core.registries.Registries;
import net.minecraft.data.worldgen.BootstapContext;
import net.minecraft.data.worldgen.placement.AquaticPlacements;
import net.minecraft.data.worldgen.placement.CavePlacements;
import net.minecraft.data.worldgen.placement.OrePlacements;
import net.minecraft.resources.ResourceKey;
import net.minecraft.sounds.SoundEvents;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.entity.MobCategory;
import net.minecraft.world.level.biome.*;
import net.minecraft.world.level.levelgen.GenerationStep;
import net.minecraft.world.level.levelgen.carver.ConfiguredWorldCarver;
import net.minecraft.world.level.levelgen.placement.PlacedFeature;

public class BiomeInit {
    public static final ResourceKey<Biome> ATLANTEAN_GARDEN_KEY = key("atlantean_garden");
    public static final ResourceKey<Biome> ATLANTIS_BIOME_KEY = key("atlantis_biome");
    public static final ResourceKey<Biome> COCONUT_ISLES_KEY = key("coconut_isles");
    public static final ResourceKey<Biome> GOO_LAGOONS_KEY = key("goo_lagoons");
    public static final ResourceKey<Biome> AQUAIEL_JELLYFISH_FIELDS_KEY = key("aquariel_jellyfish_fields");
    public static final ResourceKey<Biome> VOLCANIC_DARKSEA_KEY = key("volcanic_darksea");
    private final BootstapContext<Biome> context;

    public static ResourceKey<Biome> key(String name) {
        return ResourceKey.create(Registries.BIOME, Atlantis.id(name));
    }

    public BiomeInit(BootstapContext<Biome> context) {
        this.context = context;
        HolderGetter<PlacedFeature> holdergetter = context.lookup(Registries.PLACED_FEATURE);
        HolderGetter<ConfiguredWorldCarver<?>> holdergetter1 = context.lookup(Registries.CONFIGURED_CARVER);

        register(ATLANTEAN_GARDEN_KEY, new Biome.BiomeBuilder()
                .temperature(0.4f)
                .downfall(0.0f)
                .hasPrecipitation(false)
                .specialEffects(new BiomeSpecialEffects.Builder()
                        .skyColor(27571)
                        .fogColor(59110)
                        .waterColor(0x5CA8BC)
                        .waterFogColor(0x5CA8BC)
                        .grassColorOverride(6749952)
                        .foliageColorOverride(5373696)
                        .ambientMoodSound(new AmbientMoodSettings(
                                Holder.direct(SoundEvents.AMBIENT_UNDERWATER_LOOP),
                                6000, 8, 2))
                        .build()
                )
                .mobSpawnSettings(new MobSpawnSettings.Builder()
                        .addSpawn(MobCategory.WATER_CREATURE, new MobSpawnSettings.SpawnerData(EntityType.SQUID, 25, 2, 3))
                        .addSpawn(MobCategory.WATER_CREATURE, new MobSpawnSettings.SpawnerData(AtlantisEntityInit.RUBYCLAW_CRAB.get(), 25, 2, 4))
                        .addSpawn(MobCategory.WATER_CREATURE, new MobSpawnSettings.SpawnerData(AtlantisEntityInit.STARFISH.get(), 25, 1, 1))
                        .addSpawn(MobCategory.WATER_CREATURE, new MobSpawnSettings.SpawnerData(AtlantisEntityInit.THALASSIAN_SEAHORSE.get(), 25, 1, 1))
                        .addSpawn(MobCategory.WATER_AMBIENT, new MobSpawnSettings.SpawnerData(AtlantisEntityInit.AQUAIEL_JELLYFISH.get(), 25, 1,  1))
                        .addSpawn(MobCategory.WATER_AMBIENT, new MobSpawnSettings.SpawnerData(AtlantisEntityInit.GLITTERTAIL_SHRIMP.get(), 25, 1, 1))
                        .addSpawn(MobCategory.WATER_AMBIENT, new MobSpawnSettings.SpawnerData(EntityType.TROPICAL_FISH, 25, 4, 6))
                        .build()
                )
                .generationSettings(new BiomeGenerationSettings.Builder(holdergetter, holdergetter1)
                        .addFeature(GenerationStep.Decoration.LAKES, PlacedFeatureInit.JETSTREAM_LAKE_PLACED)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, OrePlacements.ORE_COPPER_LARGE)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, OrePlacements.ORE_ANDESITE_LOWER)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, OrePlacements.ORE_CLAY)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, OrePlacements.ORE_COAL_LOWER)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, OrePlacements.ORE_DIAMOND_BURIED)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, OrePlacements.ORE_DIORITE_LOWER)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, OrePlacements.ORE_GOLD_LOWER)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, OrePlacements.ORE_GOLD)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, OrePlacements.ORE_GOLD_EXTRA)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, OrePlacements.ORE_GRANITE_LOWER)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, OrePlacements.ORE_IRON_MIDDLE)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, OrePlacements.ORE_LAPIS_BURIED)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, OrePlacements.ORE_REDSTONE_LOWER)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, OrePlacements.ORE_TUFF)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, PlacedFeatureInit.ANCIENT_CUPRUM_PLACED)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, PlacedFeatureInit.AQUAMARINE_PLACED)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, PlacedFeatureInit.SUNKEN_GRAVEL_PLACED)
                        .addFeature(GenerationStep.Decoration.VEGETAL_DECORATION, AquaticPlacements.SEA_PICKLE)
                        .addFeature(GenerationStep.Decoration.VEGETAL_DECORATION, AquaticPlacements.WARM_OCEAN_VEGETATION)
                        .addFeature(GenerationStep.Decoration.VEGETAL_DECORATION, AquaticPlacements.SEAGRASS_DEEP_WARM)
                        .addFeature(GenerationStep.Decoration.VEGETAL_DECORATION, AquaticPlacements.SEAGRASS_SIMPLE)
                        .addFeature(GenerationStep.Decoration.VEGETAL_DECORATION, PlacedFeatureInit.SEABLOOM_PLACED)
                        .addFeature(GenerationStep.Decoration.VEGETAL_DECORATION, PlacedFeatureInit.GARDEN_FOLIAGE_PLACED)
                        .addFeature(GenerationStep.Decoration.VEGETAL_DECORATION, PlacedFeatureInit.NYMPH_TREE_PLACED)
                        .addFeature(GenerationStep.Decoration.TOP_LAYER_MODIFICATION, PlacedFeatureInit.SHELL_BLOCK_PLACED)
                        .build()
                )
                .build());

        register(ATLANTIS_BIOME_KEY, new Biome.BiomeBuilder()
                .temperature(0.5f)
                .downfall(0.0f)
                .hasPrecipitation(false)
                .specialEffects(new BiomeSpecialEffects.Builder()
                        .skyColor(27571)
                        .fogColor(59110)
                        .waterColor(0x5CA8BC)
                        .waterFogColor(0x5CA8BC)
                        .grassColorOverride(6749952)
                        .foliageColorOverride(5373696)
                        .ambientMoodSound(new AmbientMoodSettings(
                                Holder.direct(SoundEvents.AMBIENT_UNDERWATER_LOOP),
                                6000, 8, 2))
                        .build()
                )
                .mobSpawnSettings(new MobSpawnSettings.Builder()
                        //.addSpawn(MobCategory.WATER_CREATURE, new MobSpawnSettings.SpawnerData(AtlantisEntityInit.SEA_SERPENT.get(), 25, 1, 2))
                        .addSpawn(MobCategory.MONSTER, new MobSpawnSettings.SpawnerData(EntityType.DROWNED, 25, 2, 2))
                        .addSpawn(MobCategory.MONSTER, new MobSpawnSettings.SpawnerData(AtlantisEntityInit.ZOMBIE_STARFISH.get(), 25, 1, 1))
                        .addSpawn(MobCategory.MONSTER, new MobSpawnSettings.SpawnerData(EntityType.SKELETON, 25, 2, 2))
                        .addSpawn(MobCategory.WATER_CREATURE, new MobSpawnSettings.SpawnerData(EntityType.SQUID, 25, 2, 2))
                        .addSpawn(MobCategory.WATER_CREATURE, new MobSpawnSettings.SpawnerData(AtlantisEntityInit.RUBYCLAW_CRAB.get(), 25, 2, 2))
                        .addSpawn(MobCategory.WATER_CREATURE, new MobSpawnSettings.SpawnerData(AtlantisEntityInit.STARFISH.get(), 25, 1, 1))
                        .addSpawn(MobCategory.WATER_CREATURE, new MobSpawnSettings.SpawnerData(AtlantisEntityInit.THALASSIAN_SEAHORSE.get(), 25, 1, 1))
                        .addSpawn(MobCategory.WATER_AMBIENT, new MobSpawnSettings.SpawnerData(AtlantisEntityInit.AQUAIEL_JELLYFISH.get(), 25, 1, 1))
                        .addSpawn(MobCategory.WATER_AMBIENT, new MobSpawnSettings.SpawnerData(AtlantisEntityInit.GLITTERTAIL_SHRIMP.get(), 25, 2, 2))
                        .addSpawn(MobCategory.WATER_AMBIENT, new MobSpawnSettings.SpawnerData(EntityType.TROPICAL_FISH, 25, 2, 2))
                        .build()
                )
                .generationSettings(new BiomeGenerationSettings.Builder(holdergetter, holdergetter1)
                        .addFeature(GenerationStep.Decoration.LAKES, PlacedFeatureInit.JETSTREAM_LAKE_PLACED)
                        .addFeature(GenerationStep.Decoration.LOCAL_MODIFICATIONS, PlacedFeatureInit.SALT_ROCK_GEODE_PLACED)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, OrePlacements.ORE_COPPER_LARGE)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, OrePlacements.ORE_ANDESITE_LOWER)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, OrePlacements.ORE_CLAY)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, OrePlacements.ORE_COAL_LOWER)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, OrePlacements.ORE_DIAMOND_BURIED)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, OrePlacements.ORE_DIORITE_LOWER)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, OrePlacements.ORE_GOLD_LOWER)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, OrePlacements.ORE_GOLD)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, OrePlacements.ORE_GOLD_EXTRA)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, OrePlacements.ORE_GRANITE_LOWER)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, OrePlacements.ORE_IRON_MIDDLE)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, OrePlacements.ORE_LAPIS_BURIED)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, OrePlacements.ORE_REDSTONE_LOWER)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, OrePlacements.ORE_TUFF)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, PlacedFeatureInit.ANCIENT_CUPRUM_PLACED)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, PlacedFeatureInit.AQUAMARINE_PLACED)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, PlacedFeatureInit.SUNKEN_GRAVEL_PLACED)
                        .addFeature(GenerationStep.Decoration.VEGETAL_DECORATION, AquaticPlacements.SEA_PICKLE)
                        .addFeature(GenerationStep.Decoration.VEGETAL_DECORATION, AquaticPlacements.WARM_OCEAN_VEGETATION)
                        .addFeature(GenerationStep.Decoration.VEGETAL_DECORATION, AquaticPlacements.SEAGRASS_DEEP_WARM)
                        .addFeature(GenerationStep.Decoration.VEGETAL_DECORATION, AquaticPlacements.SEAGRASS_SIMPLE)
                        .addFeature(GenerationStep.Decoration.VEGETAL_DECORATION, PlacedFeatureInit.SEABLOOM_PLACED)
                        .addFeature(GenerationStep.Decoration.TOP_LAYER_MODIFICATION, PlacedFeatureInit.SHELL_BLOCK_PLACED)
                        .build()
                )
                .build());

        register(COCONUT_ISLES_KEY, new Biome.BiomeBuilder()
                .temperature(0.7f)
                .downfall(0.0f)
                .hasPrecipitation(false)
                .specialEffects(new BiomeSpecialEffects.Builder()
                        .skyColor(7907327)
                        .fogColor(12638463)
                        .waterColor(4159204)
                        .waterFogColor(329011)
                        .grassColorOverride(9170640)
                        .foliageColorOverride(5928076)
                        .ambientMoodSound(new AmbientMoodSettings(
                                SoundEvents.AMBIENT_CAVE,
                                6000, 8, 2))
                        .build()
                )
                .mobSpawnSettings(new MobSpawnSettings.Builder()
                        .addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(AtlantisEntityInit.COCONUT_CRAB.get(), 25, 2, 4))
                        .addSpawn(MobCategory.WATER_CREATURE, new MobSpawnSettings.SpawnerData(EntityType.SQUID, 5, 1, 2))
                        .addSpawn(MobCategory.WATER_CREATURE, new MobSpawnSettings.SpawnerData(AtlantisEntityInit.RUBYCLAW_CRAB.get(), 10, 1, 2))
                        .addSpawn(MobCategory.WATER_AMBIENT, new MobSpawnSettings.SpawnerData(AtlantisEntityInit.AQUAIEL_JELLYFISH.get(), 5, 1, 1))
                        .addSpawn(MobCategory.WATER_AMBIENT, new MobSpawnSettings.SpawnerData(AtlantisEntityInit.GLITTERTAIL_SHRIMP.get(), 5, 1, 1))
                        .addSpawn(MobCategory.WATER_AMBIENT, new MobSpawnSettings.SpawnerData(EntityType.TROPICAL_FISH, 10, 1, 2))
                        .build()
                )
                .generationSettings(new BiomeGenerationSettings.Builder(holdergetter, holdergetter1)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, OrePlacements.ORE_COPPER_LARGE)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, OrePlacements.ORE_ANDESITE_LOWER)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, OrePlacements.ORE_CLAY)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, OrePlacements.ORE_COAL_LOWER)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, OrePlacements.ORE_DIAMOND_BURIED)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, OrePlacements.ORE_DIORITE_LOWER)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, OrePlacements.ORE_GOLD_LOWER)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, OrePlacements.ORE_GOLD)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, OrePlacements.ORE_GOLD_EXTRA)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, OrePlacements.ORE_GRANITE_LOWER)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, OrePlacements.ORE_IRON_MIDDLE)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, OrePlacements.ORE_LAPIS_BURIED)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, OrePlacements.ORE_REDSTONE_LOWER)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, OrePlacements.ORE_TUFF)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, PlacedFeatureInit.ANCIENT_CUPRUM_PLACED)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, PlacedFeatureInit.AQUAMARINE_PLACED)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, PlacedFeatureInit.SUNKEN_GRAVEL_PLACED)
                        .addFeature(GenerationStep.Decoration.VEGETAL_DECORATION, PlacedFeatureInit.PALM_TREE_PLACED)
                        .addFeature(GenerationStep.Decoration.TOP_LAYER_MODIFICATION, PlacedFeatureInit.SHELL_BLOCK_PLACED)
                        .build()
                )
                .build());

        register(GOO_LAGOONS_KEY, new Biome.BiomeBuilder()
                .temperature(0.5f)
                .downfall(0.0f)
                .hasPrecipitation(false)
                .specialEffects(new BiomeSpecialEffects.Builder()
                        .skyColor(27571)
                        .fogColor(59110)
                        .waterColor(0x5CA8BC)
                        .waterFogColor(0x5CA8BC)
                        .grassColorOverride(6749952)
                        .foliageColorOverride(5373696)
                        .ambientMoodSound(new AmbientMoodSettings(
                                Holder.direct(SoundEvents.AMBIENT_UNDERWATER_LOOP),
                                6000, 8, 2))
                        .build()
                )
                .mobSpawnSettings(new MobSpawnSettings.Builder()
                        .addSpawn(MobCategory.MONSTER, new MobSpawnSettings.SpawnerData(EntityType.DROWNED, 25, 2, 2))
                        .addSpawn(MobCategory.MONSTER, new MobSpawnSettings.SpawnerData(EntityType.SKELETON, 25, 2, 2))
                        .addSpawn(MobCategory.WATER_CREATURE, new MobSpawnSettings.SpawnerData(EntityType.SQUID, 25, 2, 2))
                        .addSpawn(MobCategory.WATER_CREATURE, new MobSpawnSettings.SpawnerData(AtlantisEntityInit.RUBYCLAW_CRAB.get(), 25, 2, 2))
                        .addSpawn(MobCategory.WATER_CREATURE, new MobSpawnSettings.SpawnerData(AtlantisEntityInit.STARFISH.get(), 25, 1, 1))
                        .addSpawn(MobCategory.WATER_CREATURE, new MobSpawnSettings.SpawnerData(AtlantisEntityInit.THALASSIAN_SEAHORSE.get(), 25, 1, 1))
                        .addSpawn(MobCategory.WATER_AMBIENT, new MobSpawnSettings.SpawnerData(AtlantisEntityInit.AQUAIEL_JELLYFISH.get(), 25, 1, 1))
                        .addSpawn(MobCategory.WATER_AMBIENT, new MobSpawnSettings.SpawnerData(AtlantisEntityInit.GLITTERTAIL_SHRIMP.get(), 25, 1, 1))
                        .addSpawn(MobCategory.WATER_AMBIENT, new MobSpawnSettings.SpawnerData(EntityType.TROPICAL_FISH, 25, 2, 2))
                        .build()
                )
                .generationSettings(new BiomeGenerationSettings.Builder(holdergetter, holdergetter1)
                        .addFeature(GenerationStep.Decoration.LAKES, PlacedFeatureInit.SALTY_SEA_LAKE_PLACED)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, OrePlacements.ORE_COPPER_LARGE)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, OrePlacements.ORE_ANDESITE_LOWER)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, OrePlacements.ORE_CLAY)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, OrePlacements.ORE_COAL_LOWER)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, OrePlacements.ORE_DIAMOND_BURIED)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, OrePlacements.ORE_DIORITE_LOWER)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, OrePlacements.ORE_GOLD_LOWER)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, OrePlacements.ORE_GOLD)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, OrePlacements.ORE_GOLD_EXTRA)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, OrePlacements.ORE_GRANITE_LOWER)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, OrePlacements.ORE_IRON_MIDDLE)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, OrePlacements.ORE_LAPIS_BURIED)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, OrePlacements.ORE_REDSTONE_LOWER)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, OrePlacements.ORE_TUFF)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, PlacedFeatureInit.ANCIENT_CUPRUM_PLACED)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, PlacedFeatureInit.AQUAMARINE_PLACED)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, PlacedFeatureInit.SUNKEN_GRAVEL_PLACED)
                        .addFeature(GenerationStep.Decoration.VEGETAL_DECORATION, AquaticPlacements.SEA_PICKLE)
                        .addFeature(GenerationStep.Decoration.VEGETAL_DECORATION, AquaticPlacements.WARM_OCEAN_VEGETATION)
                        .addFeature(GenerationStep.Decoration.VEGETAL_DECORATION, AquaticPlacements.SEAGRASS_DEEP_WARM)
                        .addFeature(GenerationStep.Decoration.VEGETAL_DECORATION, AquaticPlacements.SEAGRASS_SIMPLE)
                        .addFeature(GenerationStep.Decoration.VEGETAL_DECORATION, PlacedFeatureInit.SEABLOOM_PLACED)
                        .addFeature(GenerationStep.Decoration.TOP_LAYER_MODIFICATION, PlacedFeatureInit.SHELL_BLOCK_PLACED)
                        .build()
                )
                .build());

        register(AQUAIEL_JELLYFISH_FIELDS_KEY, new Biome.BiomeBuilder()
                .temperature(0.5f)
                .downfall(0.0f)
                .hasPrecipitation(false)
                .specialEffects(new BiomeSpecialEffects.Builder()
                        .skyColor(27571)
                        .fogColor(59110)
                        .waterColor(0x5CA8BC)
                        .waterFogColor(0x5CA8BC)
                        .grassColorOverride(6749952)
                        .foliageColorOverride(5373696)
                        .ambientMoodSound(new AmbientMoodSettings(
                                Holder.direct(SoundEvents.AMBIENT_UNDERWATER_LOOP),
                                6000, 8, 2))
                        .build()
                )
                .mobSpawnSettings(new MobSpawnSettings.Builder()
                        .addSpawn(MobCategory.MONSTER, new MobSpawnSettings.SpawnerData(EntityType.DROWNED, 25, 2, 2))
                        .addSpawn(MobCategory.MONSTER, new MobSpawnSettings.SpawnerData(AtlantisEntityInit.ZOMBIE_STARFISH.get(), 25, 1, 1))
                        .addSpawn(MobCategory.MONSTER, new MobSpawnSettings.SpawnerData(EntityType.SKELETON, 25, 2, 2))
                        .addSpawn(MobCategory.WATER_CREATURE, new MobSpawnSettings.SpawnerData(EntityType.SQUID, 25, 2, 2))
                        .addSpawn(MobCategory.WATER_CREATURE, new MobSpawnSettings.SpawnerData(AtlantisEntityInit.RUBYCLAW_CRAB.get(), 25, 2, 2))
                        .addSpawn(MobCategory.WATER_CREATURE, new MobSpawnSettings.SpawnerData(AtlantisEntityInit.STARFISH.get(), 25, 1, 1))
                        .addSpawn(MobCategory.WATER_CREATURE, new MobSpawnSettings.SpawnerData(AtlantisEntityInit.THALASSIAN_SEAHORSE.get(), 25, 1, 1))
                        .addSpawn(MobCategory.WATER_AMBIENT, new MobSpawnSettings.SpawnerData(AtlantisEntityInit.AQUAIEL_JELLYFISH.get(), 25, 1, 1))
                        .addSpawn(MobCategory.WATER_AMBIENT, new MobSpawnSettings.SpawnerData(AtlantisEntityInit.GLITTERTAIL_SHRIMP.get(), 25, 1, 1))
                        .addSpawn(MobCategory.WATER_AMBIENT, new MobSpawnSettings.SpawnerData(EntityType.TROPICAL_FISH, 25, 2, 2))
                        .addSpawn(MobCategory.WATER_CREATURE, new MobSpawnSettings.SpawnerData(AtlantisEntityInit.LEVIATHAN.get(), 25, 2, 2))
                        .build()
                )
                .generationSettings(new BiomeGenerationSettings.Builder(holdergetter, holdergetter1)
                        .addFeature(GenerationStep.Decoration.LAKES, PlacedFeatureInit.JETSTREAM_LAKE_PLACED)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, OrePlacements.ORE_COPPER_LARGE)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, OrePlacements.ORE_ANDESITE_LOWER)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, OrePlacements.ORE_CLAY)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, OrePlacements.ORE_COAL_LOWER)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, OrePlacements.ORE_DIAMOND_BURIED)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, OrePlacements.ORE_DIORITE_LOWER)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, OrePlacements.ORE_GOLD_LOWER)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, OrePlacements.ORE_GOLD)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, OrePlacements.ORE_GOLD_EXTRA)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, OrePlacements.ORE_GRANITE_LOWER)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, OrePlacements.ORE_IRON_MIDDLE)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, OrePlacements.ORE_LAPIS_BURIED)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, OrePlacements.ORE_REDSTONE_LOWER)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, OrePlacements.ORE_TUFF)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, PlacedFeatureInit.ANCIENT_CUPRUM_PLACED)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, PlacedFeatureInit.AQUAMARINE_PLACED)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, PlacedFeatureInit.SUNKEN_GRAVEL_PLACED)
                        .addFeature(GenerationStep.Decoration.VEGETAL_DECORATION, AquaticPlacements.SEA_PICKLE)
                        .addFeature(GenerationStep.Decoration.VEGETAL_DECORATION, AquaticPlacements.WARM_OCEAN_VEGETATION)
                        .addFeature(GenerationStep.Decoration.VEGETAL_DECORATION, AquaticPlacements.SEAGRASS_DEEP_WARM)
                        .addFeature(GenerationStep.Decoration.VEGETAL_DECORATION, AquaticPlacements.SEAGRASS_SIMPLE)
                        .addFeature(GenerationStep.Decoration.VEGETAL_DECORATION, PlacedFeatureInit.SEABLOOM_PLACED)
                        .addFeature(GenerationStep.Decoration.TOP_LAYER_MODIFICATION, PlacedFeatureInit.SHELL_BLOCK_PLACED)
                        .build()
                )
                .build());

        register(VOLCANIC_DARKSEA_KEY, new Biome.BiomeBuilder()
                .temperature(0.4f)
                .downfall(0.0f)
                .hasPrecipitation(false)
                .specialEffects(new BiomeSpecialEffects.Builder()
                        .skyColor(27571)
                        .fogColor(59110)
                        .waterColor(0x5CA8BC)
                        .waterFogColor(0x5CA8BC)
                        .grassColorOverride(6749952)
                        .foliageColorOverride(5373696)
                        .ambientMoodSound(new AmbientMoodSettings(
                                Holder.direct(SoundEvents.AMBIENT_UNDERWATER_LOOP),
                                6000, 8, 2))
                        .build()
                )
                .mobSpawnSettings(new MobSpawnSettings.Builder()
                        .addSpawn(MobCategory.MONSTER, new MobSpawnSettings.SpawnerData(EntityType.DROWNED, 25, 2, 2))
                        .addSpawn(MobCategory.MONSTER, new MobSpawnSettings.SpawnerData(AtlantisEntityInit.ZOMBIE_STARFISH.get(), 25, 1, 1))
                        .addSpawn(MobCategory.MONSTER, new MobSpawnSettings.SpawnerData(EntityType.SKELETON, 25, 2, 2))
                        .addSpawn(MobCategory.WATER_CREATURE, new MobSpawnSettings.SpawnerData(EntityType.SQUID, 25, 2, 2))
                        .addSpawn(MobCategory.WATER_CREATURE, new MobSpawnSettings.SpawnerData(AtlantisEntityInit.RUBYCLAW_CRAB.get(), 25, 2, 2))
                        .addSpawn(MobCategory.WATER_CREATURE, new MobSpawnSettings.SpawnerData(AtlantisEntityInit.STARFISH.get(), 25, 2, 2))
                        .addSpawn(MobCategory.WATER_AMBIENT, new MobSpawnSettings.SpawnerData(AtlantisEntityInit.AQUAIEL_JELLYFISH.get(), 25, 2, 4))
                        .addSpawn(MobCategory.WATER_CREATURE, new MobSpawnSettings.SpawnerData(AtlantisEntityInit.LEVIATHAN.get(), 25, 2, 2))
                        .addSpawn(MobCategory.WATER_AMBIENT, new MobSpawnSettings.SpawnerData(EntityType.TROPICAL_FISH, 25, 2, 2))
                        .build()
                )
                .generationSettings(new BiomeGenerationSettings.Builder(holdergetter, holdergetter1)
                        .addFeature(GenerationStep.Decoration.RAW_GENERATION, PlacedFeatureInit.VOLCANOES_PLACED)
                        .addFeature(GenerationStep.Decoration.RAW_GENERATION, PlacedFeatureInit.GLOWSTONES_PLACED)
                        .addFeature(GenerationStep.Decoration.LAKES, PlacedFeatureInit.JETSTREAM_LAKE_PLACED)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, OrePlacements.ORE_COPPER_LARGE)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, OrePlacements.ORE_ANDESITE_LOWER)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, OrePlacements.ORE_CLAY)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, OrePlacements.ORE_COAL_LOWER)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, OrePlacements.ORE_DIAMOND_BURIED)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, OrePlacements.ORE_DIORITE_LOWER)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, OrePlacements.ORE_GOLD_LOWER)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, OrePlacements.ORE_GOLD)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, OrePlacements.ORE_GOLD_EXTRA)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, OrePlacements.ORE_GRANITE_LOWER)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, OrePlacements.ORE_IRON_MIDDLE)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, OrePlacements.ORE_LAPIS_BURIED)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, OrePlacements.ORE_REDSTONE_LOWER)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, OrePlacements.ORE_TUFF)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, PlacedFeatureInit.ANCIENT_CUPRUM_PLACED)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, PlacedFeatureInit.AQUAMARINE_PLACED)
                        .addFeature(GenerationStep.Decoration.UNDERGROUND_ORES, PlacedFeatureInit.SUNKEN_GRAVEL_PLACED)
                        .addFeature(GenerationStep.Decoration.VEGETAL_DECORATION, AquaticPlacements.SEA_PICKLE)
                        .addFeature(GenerationStep.Decoration.VEGETAL_DECORATION, AquaticPlacements.WARM_OCEAN_VEGETATION)
                        .addFeature(GenerationStep.Decoration.VEGETAL_DECORATION, AquaticPlacements.SEAGRASS_DEEP_WARM)
                        .addFeature(GenerationStep.Decoration.VEGETAL_DECORATION, AquaticPlacements.SEAGRASS_SIMPLE)
                        .addFeature(GenerationStep.Decoration.VEGETAL_DECORATION, PlacedFeatureInit.SEABLOOM_PLACED)
                        .addFeature(GenerationStep.Decoration.TOP_LAYER_MODIFICATION, CavePlacements.UNDERWATER_MAGMA)
                        .addFeature(GenerationStep.Decoration.TOP_LAYER_MODIFICATION, CavePlacements.FOSSIL_UPPER)
                        .addFeature(GenerationStep.Decoration.TOP_LAYER_MODIFICATION, PlacedFeatureInit.SHELL_BLOCK_PLACED)
                        .build()
                )
                .build());

    }

    private void register(ResourceKey<Biome> key, Biome biome) {
        context.register(key, biome);
    }
}
