# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx5G
org.gradle.daemon=false

#forge and minecraft versions
minecraft_version=1.20.1
forge_version=47.2.0

# Mod Properties
mod_name=Atlantis
mod_version = 2.18.2026-1.20.1-10.0.3-forge
maven_group = com.mystic
archives_base_name = atlantis
mapping_version = 1.20.1
mapping_channel=official
mod_authors="RedRoseWarrior1, Divinity, Safe Of Arsenal"
mod_license=ARR
mod_description=An Underwater Dimension Mod.

# Mod Dependency Versions
geckolib_version = 4711657
reflections_version = 0.10.2