org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.194
neo_version_range=[21,)
loader_version_range=[4,)
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
mod_id=atlantis
mod_name=Atlantis
mod_license=LGPLv3
mod_version=8.1.2025-1.21.1-2.0.0-neoforge
mod_group_id=com.mystic
mod_authors=Mysticpasta1, Waterpicker
mod_description=Am Underwater Dimension Mod.
geckolib_version=4.7.6