modLoader="javafml" 
loaderVersion="[47,)"
license="LGPLv3"
issueTrackerURL="https://github.com/Exploding-Creeper/atlantis/issues" 

[[mods]] 
modId="atlantis" 
version="2023.8.8-1.20.1-1.0.0-forge"
displayName="Atlantis" 
displayURL="https://github.com/Exploding-Creeper/atlantis" 
logoFile= "logo.png"
credits='''
TelepathicGrunt for his help with the JSON files,
WaterPicker for his work on the fabric branch,
LudoCrypt and Firel for the music on the music discs for atlantis,
She's Long for multiple textures, models, and jsons for assets,
and LimeShulkerBox for the Atlantean Portal and for removing the need for effects in the dimension.
'''
authors="Mysticpasta1, TelepathicGrunt, WaterPicker, BingJ, LudoCrypt, LimeShulkerBox, Divinity, She's Long, Meme Man"
description='''
An Underwater Atlantis like dimension mod.
'''

# Base
[[dependencies.atlantis]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.atlantis]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1, 1.20.2)"
    ordering="NONE"
    side="BOTH"

# Libraries
[[dependencies.atlantis]] 
    modId="cloth_config"
    mandatory=true 
    versionRange="[8.0.75,)" 
    ordering="NONE"
    side="BOTH"

[[dependencies.atlantis]] 
    modId="geckolib3"
    mandatory=false
    versionRange="[4.2.2,)"
    ordering="NONE"
    side="BOTH"