modLoader="javafml" 
loaderVersion="[47,)"
license="ARR"
issueTrackerURL="https://github.com/DimensionalDevelopment/atlantis/issues"

[[mods]] 
modId="atlantis" 
version="3.20.2026-1.20.1-11.0.0-forge"
displayName="Atlantis" 
displayURL="https://www.curseforge.com/minecraft/mc-mods/atlantis"
logoFile= "logo.png"
credits='''
TelepathicGrunt for his help with the JSON files,
WaterPicker for his work on the fabric branch,
LudoCrypt and Firel for the music on the music discs for atlantis,
She's Long for multiple textures, models, and jsons for assets,
LimeShulkerBox for the Atlantean Portal and for removing the need for effects in the dimension,
Booneraniaro for his work on the new Atlantean Structure and Revamps,
and Mysticpasta1 for creating the mod.
'''
authors="RedRoseWarrior1, Divinity, Safe Of Arsenal"
description='''
An Underwater Dimension Mod.
'''

# Base
[[dependencies.atlantis]]
    modId="forge"
    mandatory=true
    versionRange="[47.+,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.atlantis]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1, 1.20.2)"
    ordering="NONE"
    side="BOTH"

# Libraries
[[dependencies.atlantis]] 
    modId="geckolib3"
    mandatory=false
    versionRange="[4.2.2,)"
    ordering="NONE"
    side="BOTH"
